import { readFileSync } from "node:fs";
import {
  applyVersionedEnvironmentConfig,
  exportPublicEnvironmentForGithubActions,
} from "./environment-config.mjs";

const CONTRACT_URL = new URL("../config/environment-contract.json", import.meta.url);
export const ENV_CONTRACT = Object.freeze(JSON.parse(readFileSync(CONTRACT_URL, "utf8")));

export function isRequiredEnvironmentEntry(entry, env) {
  if (entry.required) return true;
  const requiredWhen = entry.requiredWhen;
  return Boolean(requiredWhen && String(env[requiredWhen.key] || "") === requiredWhen.equals);
}

export function validateEnv(env, options = {}) {
  const errors = [];
  const allowMissingProvisioned = options.allowMissingProvisioned ?? false;
  for (const entry of ENV_CONTRACT) {
    const value = env[entry.key];
    const required = isRequiredEnvironmentEntry(entry, env);
    if (value === undefined || value === "") {
      if (required && !(allowMissingProvisioned && entry.provisioned)) {
        errors.push(`missing required: ${entry.key} (${entry.hint})`);
      }
      continue;
    }
    if (!validValue(String(value), entry.validator)) {
      errors.push(`malformed: ${entry.key} (${entry.hint})`);
    }
  }
  return { ok: errors.length === 0, errors };
}

export function renderDotenv(env) {
  const lines = ["# Generated by scripts/generate-env.mjs — do not commit."];
  for (const entry of ENV_CONTRACT) {
    if (entry.deployOnly) continue;
    const value = env[entry.key];
    if (value === undefined || value === "") continue;
    lines.push(`${entry.key}=${formatDotenvValue(value)}`);
  }
  return `${lines.join("\n")}\n`;
}

function validValue(value, validator = { type: "nonempty" }) {
  if (validator.type === "nonempty") return value.trim().length > 0;
  if (validator.type === "prefix") return value.startsWith(validator.value);
  if (validator.type === "enum") return validator.values.includes(value);
  if (validator.type === "boolean-string") return value === "true" || value === "false";
  if (validator.type === "pattern") return new RegExp(validator.value).test(value);
  if (validator.type === "email") return /^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(value);
  if (validator.type === "url") {
    try {
      const parsed = new URL(value);
      return !validator.protocols || validator.protocols.includes(parsed.protocol);
    } catch {
      return false;
    }
  }
  return true;
}

function formatDotenvValue(value) {
  const stringValue = String(value);
  if (/[\s#"'\\]/.test(stringValue)) return `"${stringValue.replaceAll("\\", "\\\\").replaceAll('"', '\\"')}"`;
  return stringValue;
}

export function parseDotenv(content) {
  const parsed = {};
  for (const rawLine of content.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;
    const equalsAt = line.indexOf("=");
    if (equalsAt <= 0) continue;
    const key = line.slice(0, equalsAt).trim();
    let value = line.slice(equalsAt + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1).replaceAll('\\"', '"').replaceAll("\\\\", "\\");
    }
    parsed[key] = value;
  }
  return parsed;
}

export async function loadLocalDotenv(env = process.env, path) {
  if (String(env.MARKETPLACE_DISABLE_LOCAL_DOTENV || "") === "true") return false;
  const { readFile } = await import("node:fs/promises");
  const paths = path ? [path] : [".env.local", ".env"];
  let loaded = false;
  for (const candidate of paths) {
    try {
      const parsed = parseDotenv(await readFile(candidate, "utf8"));
      for (const [key, value] of Object.entries(parsed)) {
        if (env[key] === undefined || env[key] === "") env[key] = value;
      }
      loaded = true;
    } catch (error) {
      if (error?.code !== "ENOENT") throw error;
    }
  }
  return loaded;
}

async function main() {
  const [, , mode, outPath] = process.argv;
  const allowMissingProvisioned = process.argv.includes("--allow-missing-provisioned");
  await loadLocalDotenv(process.env);
  const appliedConfig = await applyVersionedEnvironmentConfig(process.env);
  if (appliedConfig.length > 0) console.log(`resolved public environment config: ${appliedConfig.join(", ")}`);

  if (mode === "--export-public") {
    await exportPublicEnvironmentForGithubActions(process.env, ENV_CONTRACT);
    return;
  }

  const { ok, errors } = validateEnv(process.env, { allowMissingProvisioned });
  if (!ok) {
    console.error("Environment contract validation FAILED:");
    for (const error of errors) console.error(`  - ${error}`);
    console.error("See docs/generated/environment-reference.md for the generated source-of-truth table.");
    process.exit(1);
  }

  if (process.env.GITHUB_ACTIONS) {
    const exported = await exportPublicEnvironmentForGithubActions(process.env, ENV_CONTRACT);
    if (exported.length > 0) console.log(`exported public environment keys to GitHub Actions: ${exported.join(", ")}`);
  }

  if (mode === "--write") {
    const { writeFile, chmod } = await import("node:fs/promises");
    const target = outPath || ".env";
    await writeFile(target, renderDotenv(process.env), "utf8");
    await chmod(target, 0o600);
    const written = ENV_CONTRACT.filter((entry) => !entry.deployOnly && process.env[entry.key]).map((entry) => entry.key);
    console.log(`wrote ${target} with keys: ${written.join(", ")}`);
  } else if (mode === "--check" || mode === undefined) {
    console.log("environment contract OK");
  } else {
    console.error(`unknown mode: ${mode} (use --check, --write, or --export-public)`);
    process.exit(2);
  }
}

if (import.meta.url === `file://${process.argv[1]}`) await main();
