/**
 * generate-env.mjs — the single source of truth for the environment
 * contract, and the bridge between GitHub Environment secrets/vars
 * and a runnable `.env`.
 *
 * Dependency-free on purpose: CI can run it before `npm install`.
 * The zod schema in lib/env.ts mirrors this contract for app runtime.
 *
 * Usage:
 *   node scripts/generate-env.mjs --check           # validate process.env, exit 1 on failure
 *   node scripts/generate-env.mjs --write [path]    # validate, then write .env (default ./.env)
 *
 * If a local .env file exists, it is loaded before validation without
 * overriding already-exported environment variables.
 *
 * Security invariants:
 *   * Secret VALUES are never printed — only key names.
 *   * The written .env is chmod 600 and is gitignored.
 */

/**
 * The contract. `secret: true` keys belong in GitHub Environment
 * *secrets*; the rest are non-secret *vars*. `deployOnly` keys are
 * consumed by the deploy workflow itself and are not written to .env.
 * Keep this table in sync with .env.example and docs/environments.md.
 */
export const ENV_CONTRACT = [
  // --- Supabase ---
  {
    key: "NEXT_PUBLIC_SUPABASE_URL",
    required: true,
    secret: false,
    pattern: /^https:\/\/.+/,
    hint: "https://<project-ref>.supabase.co",
  },
  {
    key: "NEXT_PUBLIC_SUPABASE_ANON_KEY",
    required: true,
    secret: false,
    hint: "anon/publishable key (RLS-enforced)",
  },
  {
    key: "SUPABASE_SERVICE_ROLE_KEY",
    required: true,
    secret: true,
    hint: "service role key — bypasses RLS, server only",
  },
  // --- Stripe ---
  {
    key: "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY",
    required: true,
    secret: false,
    pattern: /^pk_/,
    hint: "pk_test_... in dev/staging, pk_live_... in production",
  },
  {
    key: "STRIPE_SECRET_KEY",
    required: true,
    secret: true,
    pattern: /^sk_/,
    hint: "sk_test_... in dev/staging, sk_live_... in production",
  },
  {
    key: "STRIPE_WEBHOOK_SECRET",
    required: true,
    secret: true,
    pattern: /^whsec_/,
    hint: "from the Stripe webhook endpoint config",
  },
  // --- App ---
  {
    key: "NEXT_PUBLIC_SITE_URL",
    required: true,
    secret: false,
    pattern: /^https?:\/\/.+/,
    hint: "canonical public URL of this environment",
  },
  // --- Deploy-time only (not written to .env) ---
  {
    key: "TARGET_ENV",
    required: true,
    secret: false,
    deployOnly: true,
    pattern: /^(development|staging|production)$/,
    hint: "GitHub Environment name; must match the workflow target",
  },
  {
    key: "SUPABASE_ACCESS_TOKEN",
    required: false,
    secret: true,
    deployOnly: true,
    hint: "Supabase CLI auth for `supabase db push`",
  },
  {
    key: "SUPABASE_DB_PASSWORD",
    required: false,
    secret: true,
    deployOnly: true,
    hint: "database password for `supabase link`",
  },
  {
    key: "SUPABASE_PROJECT_REF",
    required: false,
    secret: false,
    deployOnly: true,
    hint: "project ref for `supabase link`",
  },
  { key: "VERCEL_TOKEN", required: false, secret: true, deployOnly: true, hint: "Vercel CLI auth" },
  { key: "VERCEL_ORG_ID", required: false, secret: false, deployOnly: true, hint: "Vercel org id" },
  {
    key: "VERCEL_PROJECT_ID",
    required: false,
    secret: false,
    deployOnly: true,
    hint: "Vercel project id",
  },
  // --- Notifications (optional; a missing key disables the channel) ---
  { key: "RESEND_API_KEY", required: false, secret: true, hint: "email via Resend" },
  {
    key: "RESEND_FROM_EMAIL",
    required: false,
    secret: false,
    pattern: /^[^@\s]+@[^@\s]+\.[^@\s]+$/,
    hint: "verified Resend sender address",
  },
  {
    key: "SUPPORT_EMAIL",
    required: false,
    secret: false,
    pattern: /^[^@\s]+@[^@\s]+\.[^@\s]+$/,
    hint: "support contact shown in transactional emails",
  },
  { key: "TWILIO_ACCOUNT_SID", required: false, secret: false, hint: "SMS via Twilio" },
  { key: "TWILIO_AUTH_TOKEN", required: false, secret: true, hint: "SMS via Twilio" },
  { key: "TELEGRAM_BOT_TOKEN", required: false, secret: true, hint: "Telegram Bot API" },
  { key: "WHATSAPP_ACCESS_TOKEN", required: false, secret: true, hint: "WhatsApp Cloud API" },
];

/**
 * Validate an env object against the contract.
 * Returns { ok, errors } — errors mention key NAMES only, never values.
 */
export function validateEnv(env) {
  const errors = [];
  for (const entry of ENV_CONTRACT) {
    const value = env[entry.key];
    if (value === undefined || value === "") {
      if (entry.required) errors.push(`missing required: ${entry.key} (${entry.hint})`);
      continue;
    }
    if (entry.pattern && !entry.pattern.test(value)) {
      errors.push(`malformed: ${entry.key} — expected ${entry.pattern} (${entry.hint})`);
    }
  }
  return { ok: errors.length === 0, errors };
}

/** Render .env content from an env object (runtime keys only). */
export function renderDotenv(env) {
  const lines = ["# Generated by scripts/generate-env.mjs — do not commit."];
  for (const entry of ENV_CONTRACT) {
    if (entry.deployOnly) continue;
    const value = env[entry.key];
    if (value === undefined || value === "") continue;
    lines.push(`${entry.key}=${value}`);
  }
  return lines.join("\n") + "\n";
}

export function parseDotenv(content) {
  const parsed = {};
  for (const rawLine of content.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;

    const equalsAt = line.indexOf("=");
    if (equalsAt <= 0) continue;

    const key = line.slice(0, equalsAt).trim();
    let value = line.slice(equalsAt + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    parsed[key] = value;
  }
  return parsed;
}

export async function loadLocalDotenv(env = process.env, path = ".env") {
  try {
    const { readFile } = await import("node:fs/promises");
    const parsed = parseDotenv(await readFile(path, "utf8"));
    for (const [key, value] of Object.entries(parsed)) {
      if (env[key] === undefined) env[key] = value;
    }
    return true;
  } catch (error) {
    if (error?.code === "ENOENT") return false;
    throw error;
  }
}

async function main() {
  const [, , mode, outPath] = process.argv;
  await loadLocalDotenv(process.env);
  const { ok, errors } = validateEnv(process.env);

  if (!ok) {
    console.error("Environment contract validation FAILED:");
    for (const e of errors) console.error(`  - ${e}`);
    console.error("See docs/environments.md for where each key comes from.");
    process.exit(1);
  }

  if (mode === "--write") {
    const { writeFile, chmod } = await import("node:fs/promises");
    const target = outPath || ".env";
    await writeFile(target, renderDotenv(process.env), "utf8");
    await chmod(target, 0o600);
    const written = ENV_CONTRACT.filter((e) => !e.deployOnly && process.env[e.key]).map(
      (e) => e.key
    );
    console.log(`wrote ${target} with keys: ${written.join(", ")}`);
  } else if (mode === "--check" || mode === undefined) {
    console.log("environment contract OK");
  } else {
    console.error(`unknown mode: ${mode} (use --check or --write)`);
    process.exit(2);
  }
}

// Only run as a CLI, not when imported by tests.
if (import.meta.url === `file://${process.argv[1]}`) {
  await main();
}
