import {
  applyVersionedEnvironmentConfig,
  exportPublicEnvironmentForGithubActions,
} from "./environment-config.mjs";

export const ENV_CONTRACT = [
  { key: "NEXT_PUBLIC_SUPABASE_URL", required: true, secret: false, pattern: /^https:\/\/.+/, hint: "Supabase project API URL" },
  { key: "NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY", required: true, secret: false, hint: "Supabase publishable key" },
  { key: "SUPABASE_SECRET_KEY", required: true, secret: true, hint: "Supabase server key" },
  { key: "SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_ID", required: false, secret: false, hint: "local Supabase Google OAuth client id" },
  { key: "SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_SECRET", required: false, secret: true, hint: "local Supabase Google OAuth client secret" },
  { key: "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY", required: true, secret: false, pattern: /^pk_/, hint: "Stripe publishable key" },
  { key: "STRIPE_SECRET_KEY", required: true, secret: true, pattern: /^sk_/, hint: "Stripe server key" },
  { key: "STRIPE_WEBHOOK_SECRET", required: true, secret: true, pattern: /^whsec_/, hint: "Stripe webhook signing key" },
  { key: "NEXT_PUBLIC_SITE_URL", required: true, secret: false, pattern: /^https?:\/\/.+/, hint: "canonical public URL" },
  { key: "APP_NAME", required: true, secret: false, pattern: /\S/, hint: "display name" },
  { key: "TARGET_ENV", required: true, secret: false, deployOnly: true, pattern: /^(development|production)$/, hint: "deployment environment" },
  { key: "SUPABASE_ACCESS_TOKEN", required: false, secret: true, deployOnly: true, hint: "Supabase CLI access" },
  { key: "SUPABASE_DB_PASSWORD", required: false, secret: true, deployOnly: true, hint: "Supabase database credential" },
  { key: "SUPABASE_PROJECT_REF", required: false, secret: false, deployOnly: true, hint: "Supabase project reference" },
  { key: "GOOGLE_OAUTH_CLIENT_ID", required: false, secret: false, deployOnly: true, hint: "hosted Supabase Google OAuth client id" },
  { key: "GOOGLE_OAUTH_CLIENT_SECRET", required: false, secret: true, deployOnly: true, hint: "hosted Supabase Google OAuth client secret" },
  { key: "STRIPE_WEBHOOK_ENDPOINT_ID", required: false, secret: false, deployOnly: true, pattern: /^we_/, hint: "managed Stripe webhook endpoint id" },
  { key: "STRIPE_WEBHOOK_ENABLED_EVENTS", required: false, secret: false, deployOnly: true, hint: "comma or whitespace separated Stripe webhook event override" },
  { key: "VERCEL_TOKEN", required: false, secret: true, deployOnly: true, hint: "Vercel CLI access" },
  { key: "VERCEL_ORG_ID", required: false, secret: false, deployOnly: true, hint: "Vercel deploy scope id: personal user id for Hobby or team/org id later" },
  { key: "VERCEL_PROJECT_ID", required: false, secret: false, deployOnly: true, hint: "Vercel project id" },
  { key: "RESEND_API_KEY", required: false, secret: true, hint: "email provider" },
  { key: "RESEND_FROM_EMAIL", required: false, secret: false, pattern: /^[^@\s]+@[^@\s]+\.[^@\s]+$/, hint: "sender email" },
  { key: "SUPPORT_EMAIL", required: false, secret: false, pattern: /^[^@\s]+@[^@\s]+\.[^@\s]+$/, hint: "support email" },
  { key: "TWILIO_ACCOUNT_SID", required: false, secret: false, hint: "SMS provider account" },
  { key: "TWILIO_AUTH_TOKEN", required: false, secret: true, hint: "SMS provider token" },
  { key: "TELEGRAM_BOT_TOKEN", required: false, secret: true, hint: "Telegram provider token" },
  { key: "WHATSAPP_ACCESS_TOKEN", required: false, secret: true, hint: "WhatsApp provider token" },
  { key: "WHATSAPP_PHONE_NUMBER_ID", required: false, secret: false, hint: "WhatsApp phone-number id" },
];

export function validateEnv(env) {
  const errors = [];
  for (const entry of ENV_CONTRACT) {
    const value = env[entry.key];
    if (value === undefined || value === "") {
      if (entry.required) errors.push(`missing required: ${entry.key} (${entry.hint})`);
      continue;
    }
    if (entry.pattern && !entry.pattern.test(value)) {
      errors.push(`malformed: ${entry.key} — expected ${entry.pattern} (${entry.hint})`);
    }
  }
  return { ok: errors.length === 0, errors };
}

export function renderDotenv(env) {
  const lines = ["# Generated by scripts/generate-env.mjs — do not commit."];
  for (const entry of ENV_CONTRACT) {
    if (entry.deployOnly) continue;
    const value = env[entry.key];
    if (value === undefined || value === "") continue;
    lines.push(`${entry.key}=${formatDotenvValue(value)}`);
  }
  return lines.join("\n") + "\n";
}

function formatDotenvValue(value) {
  if (/[\s#"'\\]/.test(value)) return `"${value.replaceAll("\\", "\\\\").replaceAll('"', '\\"')}"`;
  return value;
}

export function parseDotenv(content) {
  const parsed = {};
  for (const rawLine of content.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;
    const equalsAt = line.indexOf("=");
    if (equalsAt <= 0) continue;
    const key = line.slice(0, equalsAt).trim();
    let value = line.slice(equalsAt + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) value = value.slice(1, -1);
    parsed[key] = value;
  }
  return parsed;
}

export async function loadLocalDotenv(env = process.env, path = ".env") {
  try {
    const { readFile } = await import("node:fs/promises");
    const parsed = parseDotenv(await readFile(path, "utf8"));
    for (const [key, value] of Object.entries(parsed)) if (env[key] === undefined || env[key] === "") env[key] = value;
    return true;
  } catch (error) {
    if (error?.code === "ENOENT") return false;
    throw error;
  }
}

async function main() {
  const [, , mode, outPath] = process.argv;
  await loadLocalDotenv(process.env);
  const appliedConfig = await applyVersionedEnvironmentConfig(process.env);
  const { ok, errors } = validateEnv(process.env);

  if (!ok) {
    console.error("Environment contract validation FAILED:");
    for (const e of errors) console.error(`  - ${e}`);
    console.error("See docs/environments.md for where each key comes from.");
    process.exit(1);
  }

  if (process.env.GITHUB_ACTIONS) {
    const exported = await exportPublicEnvironmentForGithubActions(process.env, ENV_CONTRACT);
    if (exported.length > 0) console.log(`exported public environment keys to GitHub Actions: ${exported.join(", ")}`);
  }

  if (appliedConfig.length > 0) {
    console.log(`resolved public environment config: ${appliedConfig.join(", ")}`);
  }

  if (mode === "--write") {
    const { writeFile, chmod } = await import("node:fs/promises");
    const target = outPath || ".env";
    await writeFile(target, renderDotenv(process.env), "utf8");
    await chmod(target, 0o600);
    const written = ENV_CONTRACT.filter((e) => !e.deployOnly && process.env[e.key]).map((e) => e.key);
    console.log(`wrote ${target} with keys: ${written.join(", ")}`);
  } else if (mode === "--check" || mode === undefined) {
    console.log("environment contract OK");
  } else {
    console.error(`unknown mode: ${mode} (use --check or --write)`);
    process.exit(2);
  }
}

if (import.meta.url === `file://${process.argv[1]}`) await main();
