name: Deploy (reusable)

on:
  workflow_call:
    inputs:
      environment:
        description: GitHub Environment to deploy (development | staging | production)
        required: true
        type: string

permissions:
  contents: read

jobs:
  validate-env:
    runs-on: ubuntu-latest
    steps:
      - run: echo ok
