name: Deploy production

on:
  release:
    types: [published]
  push:
    tags: ['v*']

concurrency:
  group: marketplace-environment-production
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: production
    secrets: inherit
