name: Deploy staging

on:
  workflow_dispatch:
  push:
    branches: [main]

concurrency:
  group: marketplace-environment-staging
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: staging
    secrets: inherit
